//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFirstApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobitem
    {
        public int jobs_jobID { get; set; }
        public int items_itemID { get; set; }
        public Nullable<int> usedQuantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual job job { get; set; }
    }
}
